// ORDER ACTIONS
export const ORDER_POKE = 'ORDER_POKE';
export const ORDER_FULFILLED = 'ORDER_FULFILLED';
export const ORDER_STARTED = 'ORDER_STARTED';
export const ORDER_CANCELLED = 'ORDER_CANCELLED';
export const ORDER_CREATED = 'ORDER_CREATED';

export const UI_INVENTORY_FILTER_TOGGLE = 'UI_INVENTORY_FILTER_TOGGLE';
export const UI_INVENTORY_FILTER_RESET = 'UI_INVENTORY_FILTER_RESET';

